### ISSUE TITLE
filebeat report errors in the log

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-integration-testing#636]
`./scripts/compose.py start master --with-opbeans-java --with-filebeat`

```
{"level":"error","timestamp":"2019-10-17T17:41:37.235Z","caller":"readjson/json.go:52","message":"Error decoding JSON: json: cannot unmarshal number into Go value of type map[string]interface {}"}
{"level":"error","timestamp":"2019-10-17T17:41:38.852Z","logger":"autodiscover","caller":"cfgfile/list.go:96","message":"Error creating runner from config: Can only start an input when all related states are finished: {Id:2395809-2049 Finished:false Fileinfo:0xc0007561a0 Source:/var/lib/docker/containers/d9da67140c825712499ecc333458d990d0b1082702a954761683792d21782bbd/d9da67140c825712499ecc333458d990d0b1082702a954761683792d21782bbd-json.log Offset:609552 Timestamp:2019-10-17 17:41:36.79576 +0000 UTC m=+256.293930701 TTL:-1ns Type:docker Meta:map[] FileStateOS:2395809-2049}"}
```

**Comment by kuisathaverat** [comment]
there are some log messages that are not JSON 

```
{"log":"2019-10-17 17:55:04.803 [apm-remote-config-poller] INFO co.elastic.apm.agent.configuration.ApmServerConfigurationSource - Received new configuration from APM Server: {}\n","stream":"stdout","time":"2019-10-17T17:55:04.8041885Z"}
```

The configuration should ignore them but I am not sure

```
        - condition:
            contains:
              docker.container.image: "opbeans-java"
          config:
            - type: docker
              containers.ids:
                - "${data.docker.container.id}"
              processors:
                - if:
                    regexp:
                      message: '^\{.*\}$'
                  then:
                    - decode_json_fields:
                        fields:
                          - message
                        target: ""
                        overwrite_keys: true
              fields_under_root: true
```

**Comment by kuisathaverat** [comment]
It is reading the logs of all containers on every container config, I think it is related to the path setting `- '/var/lib/docker/containers/*/*.log'`


```
        - condition:
            contains:
              docker.container.image: "opbeans-java"
          config:
            - type: container
              paths:
                - '/var/lib/docker/containers/*/*.log'
              containers.ids:
                - "${data.docker.container.id}"
              tail_files: true
              tags: ["opbeans-java"]
```

<img width="1493" alt="Screenshot 2019-10-18 at 12 45 38" src="https://user-images.githubusercontent.com/5400788/67088360-415ca800-f1a5-11e9-8b15-acfd27cdc267.png">
