### ISSUE TITLE
Improve readability of generated docker-compose.yml

### ISSUE THREAD

**Issue by axw** [elastic/apm-integration-testing#712]
The docker-compose.yml file that is currently generated by compose.py is JSON, a subset of YAML. While it's technically YAML, it's not the best kind of YAML – it's hard to read, and hard to edit by hand.

For this, I propose we introduce an optional dependency on PyYAML, and add a flag to output in YAML. Ideally the output would look like a typical hand-crafted file, with the version at the top, volumes at the bottom, etc.

Another thing that makes the output difficult to read is the inclusion of redundant config, and config only relevant to running integration tests. It would be nice if we could generate a minimal docker-compose.yml for other purposes, such as in "quick start" documentation (https://github.com/elastic/apm-server/pull/3106).

For this I propose we stop explicitly specifying default config, and provide another new flag to set only the minimally required config for starting up the Stack and APM Server.

See https://gist.github.com/axw/05e6fb7f97108cb752b3051a0b304d2b as an example.

**Comment by kuisathaverat** [comment]
This is the minimal output right now, to rid of all related option from integration test would need to add tons of `if` to remove those options, I am not sure it worths

`scripts/compose.py start 7.6 `

```yaml
---
networks:
  default: {name: apm-integration-testing}
services:
  apm-server:
    cap_add: [CHOWN, DAC_OVERRIDE, SETGID, SETUID]
    cap_drop: [ALL]
    command: [apm-server, -e, --httpprof, ':6060', -E, apm-server.rum.enabled=true,
      -E, apm-server.rum.event_rate.limit=1000, -E, 'apm-server.host=0.0.0.0:8200',
      -E, apm-server.read_timeout=1m, -E, apm-server.shutdown_timeout=2m, -E, apm-server.write_timeout=1m,
      -E, logging.json=true, -E, logging.metrics.enabled=false, -E, 'setup.kibana.host=kibana:5601',
      -E, setup.template.settings.index.number_of_replicas=0, -E, setup.template.settings.index.number_of_shards=1,
      -E, setup.template.settings.index.refresh_interval=1ms, -E, monitoring.elasticsearch=true,
      -E, monitoring.enabled=true, -E, apm-server.instrumentation.enabled=true, -E,
      apm-server.instrumentation.profiling.cpu.enabled=true, -E, apm-server.instrumentation.profiling.heap.enabled=true,
      -E, apm-server.kibana.enabled=true, -E, 'apm-server.kibana.host=kibana:5601',
      -E, apm-server.agent.config.cache.expiration=30s, -E, apm-server.kibana.username=apm_server_user,
      -E, apm-server.kibana.password=changeme, -E, apm-server.jaeger.http.enabled=true,
      -E, 'apm-server.jaeger.http.host=0.0.0.0:14268', -E, apm-server.jaeger.grpc.enabled=true,
      -E, 'apm-server.jaeger.grpc.host=0.0.0.0:14250', -E, 'output.elasticsearch.hosts=["elasticsearch:9200"]',
      -E, output.elasticsearch.username=apm_server_user, -E, output.elasticsearch.password=changeme,
      -E, output.elasticsearch.enabled=true, -E, 'output.elasticsearch.pipelines=[{pipeline:
        ''apm''}]', -E, apm-server.register.ingest.pipeline.enabled=true]
    container_name: localtesting_7.6_apm-server
    depends_on:
      elasticsearch: {condition: service_healthy}
      kibana: {condition: service_healthy}
    healthcheck:
      interval: 10s
      retries: 12
      test: [CMD, curl, --write-out, '''HTTP %{http_code}''', --fail, --silent, --output,
        /dev/null, 'http://localhost:8200/']
    image: docker.elastic.co/apm/apm-server:7.6-SNAPSHOT
    labels: [co.elastic.apm.stack-version=7.6]
    logging:
      driver: json-file
      options: {max-file: '5', max-size: 2m}
    ports: ['127.0.0.1:8200:8200', '127.0.0.1:6060:6060', '127.0.0.1:14268:14268',
      '127.0.0.1:14250:14250']
  elasticsearch:
    container_name: localtesting_7.6_elasticsearch
    environment: [bootstrap.memory_lock=true, cluster.name=docker-cluster, cluster.routing.allocation.disk.threshold_enabled=false,
      discovery.type=single-node, path.repo=/usr/share/elasticsearch/data/backups,
      'ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g', path.data=/usr/share/elasticsearch/data/7.6,
      xpack.security.authc.anonymous.roles=remote_monitoring_collector, xpack.security.authc.realms.file.file1.order=0,
      xpack.security.authc.realms.native.native1.order=1, xpack.security.authc.token.enabled=true,
      xpack.security.authc.api_key.enabled=true, xpack.security.enabled=true, xpack.license.self_generated.type=trial,
      xpack.monitoring.collection.enabled=true]
    healthcheck:
      interval: '20'
      retries: 10
      test: [CMD-SHELL, 'curl -s http://localhost:9200/_cluster/health | grep -vq
          ''"status":"red"''']
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6-SNAPSHOT
    labels: [co.elastic.apm.stack-version=7.6]
    logging:
      driver: json-file
      options: {max-file: '5', max-size: 2m}
    ports: ['127.0.0.1:9200:9200']
    ulimits:
      memlock: {hard: -1, soft: -1}
    volumes: ['esdata:/usr/share/elasticsearch/data', './docker/elasticsearch/roles.yml:/usr/share/elasticsearch/config/roles.yml',
      './docker/elasticsearch/users:/usr/share/elasticsearch/config/users', './docker/elasticsearch/users_roles:/usr/share/elasticsearch/config/users_roles']
  kibana:
    container_name: localtesting_7.6_kibana
    depends_on:
      elasticsearch: {condition: service_healthy}
    environment: {ELASTICSEARCH_PASSWORD: changeme, ELASTICSEARCH_URL: 'elasticsearch:9200',
      ELASTICSEARCH_USERNAME: kibana_system_user, SERVER_NAME: kibana.example.org,
      STATUS_ALLOWANONYMOUS: 'true', XPACK_MONITORING_ENABLED: 'true', XPACK_SECURITY_LOGINASSISTANCEMESSAGE: 'Login&#32;details:&#32;`kibana_system_user/changeme`.&#32;Further&#32;details&#32;[here](https://github.com/elastic/apm-integration-testing#logging-in).',
      XPACK_XPACK_MAIN_TELEMETRY_ENABLED: 'false'}
    healthcheck:
      interval: 10s
      retries: 20
      test: [CMD, curl, --write-out, '''HTTP %{http_code}''', --fail, --silent, --output,
        /dev/null, 'http://kibana:5601/api/status']
    image: docker.elastic.co/kibana/kibana:7.6-SNAPSHOT
    labels: [co.elastic.apm.stack-version=7.6]
    logging:
      driver: json-file
      options: {max-file: '5', max-size: 2m}
    ports: ['127.0.0.1:5601:5601']
version: '2.1'
volumes:
  esdata: {driver: local}
  pgdata: {driver: local}

```
